name: CI Workflow

on:
  push:
    branches:
      - master

env:
  ENVIRONMENT: Prod  # Setting the environment variable directly using the env keyword

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the application
        run: echo "Building in $ENVIRONMENT"
      - name: Push the docker image
        run: echo "Pushing the docker image"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build the application
        run: echo "Deploying in $ENVIRONMENT"  